version: '3'
services:
  scp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scp
    restart: unless-stopped
    network_mode: host  # Use host network
    volumes:
      - "./config:/root/.config/SCP Secret Laboratory/config"
      - "./plugins:/root/.config/EXILED/Plugins"
    tty: true
    stdin_open: true
