version: '3'
services:
  scp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scp
    restart: unless-stopped
    ports:
      - "7777:7777"
    volumes:
      - "./config:/home/steam/.config/SCP Secret Laboratory/config"
    tty: true
