version: '3'
services:
  scp:
    image: valgul/scp
    container_name: scp
    restart: unless-stopped
    network_mode: host  # Use host network
    volumes:
      - "./config:/root/.config/SCP Secret Laboratory/config"
    tty: true
    stdin_open: true
