name: Build & Publish SCP Exiled Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "scp_exiled"
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./scp/exiled
          push: true
          platforms: linux/amd64
          tags: valgul/scp:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max